version: '3.8'

services:
  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "3000:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G  
    command: "-p default_keep=300"
    depends_on:
      - backend
  backend:
    container_name: backend-dagon
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    build:
      context: ./backend
    expose:
      - "3000"
    # using env file
    env_file: ./backend/.env  
    # overwrited env variables:
    environment: 
      - FRONTENDURL=http://localhost  
      - MONGO_URI=mongodb://mongo:27017/mydatabase 
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: frontend-dagon
    environment: 
      - VITE_API_URL=http://localhost:3000
      - VITE_URL=http://localhost
    # share a volume
    volumes:
      - images-folder:/app/images
      - frontend-folder:/app/dist
    depends_on:
      - backend
  
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_cache:/data/nginx/cache
      - images-folder:/data/images
      - frontend-folder:/usr/share/nginx/html
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - frontend
      - backend
          # networks:
    #   - internal_network
    #   - public_network
  mongo:
    image: mongo:5.0
    container_name: mongo-dagon
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
  images-folder:
  frontend-folder:
# networks:
#   internal_network:
#     internal: true
#   public_network: